resources:
  repositories:
    - repository: templates
      type: github
      name: Omnicit/AzurePipelineTemplates
      endpoint: Github

variables:
- group: deployment-vars

trigger:
  branches:
    include:
    - refs/heads/*

stages:
- template: BuildTestDeployModule.yml@templates
